use serde::{Deserialize, Serialize};
use chrono::{DateTime, Utc};
use std::collections::HashMap;

/// Content strategy for a marketing campaign.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ContentStrategy {
    pub id: String,
    pub name: String,
    pub target_audience: String,
    pub tone: ContentTone,
    pub platforms: Vec<String>,
    pub content_pillars: Vec<String>,
    pub posting_frequency: HashMap<String, u32>, // platform -> posts per week
    pub created_at: DateTime<Utc>,
}

/// Tone for content generation.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ContentTone {
    Professional,
    Casual,
    Technical,
    Inspirational,
    Educational,
    Humorous,
}

/// A content piece generated by the marketing agent.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ContentPiece {
    pub id: String,
    pub strategy_id: String,
    pub platform: String,
    pub content: String,
    pub hashtags: Vec<String>,
    pub media_suggestions: Vec<String>,
    pub generated_at: DateTime<Utc>,
    pub approved: bool,
}

/// Marketing analytics summary.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MarketingReport {
    pub period_start: DateTime<Utc>,
    pub period_end: DateTime<Utc>,
    pub total_posts: u32,
    pub total_impressions: u64,
    pub total_engagement: u64,
    pub top_performing_posts: Vec<String>,
    pub platform_breakdown: HashMap<String, PlatformMetrics>,
}

/// Per-platform metrics.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PlatformMetrics {
    pub posts: u32,
    pub impressions: u64,
    pub engagement: u64,
    pub avg_engagement_rate: f64,
}
