/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Configuration object for headless / CI use.
 *
 * ```typescript
 * import { PylotAgent, Config } from 'pylot';
 *
 * const config = new Config({
 *   llmProvider: 'anthropic',
 *   llmModel: 'claude-sonnet-4-20250514',
 *   anthropicApiKey: process.env.ANTHROPIC_API_KEY,
 * });
 * const agent = new PylotAgent(config);
 * ```
 */
export interface Config {
  llmProvider: string
  llmModel: string
  openaiApiKey?: string
  anthropicApiKey?: string
  googleCredentialsFile?: string
  telegramBotToken?: string
  telegramChatId?: string
}
export interface MemorySearchResult {
  id: string
  content: string
  score: number
}
export interface SkillInfo {
  name: string
  hasSkillFile: boolean
}
export interface LearnedRuleInfo {
  id: string
  ruleText: string
  confidence: number
}
/**
 * The primary OpenPylot class exposed to Node.js / TypeScript.
 *
 * ```typescript
 * import { PylotAgent } from 'pylot';
 *
 * // First-time interactive setup
 * await PylotAgent.init();
 *
 * // Or load from existing config
 * const agent = await PylotAgent.fromConfig('~/.pylot/secrets.enc');
 * const response = await agent.chat('What meetings do I have today?');
 * console.log(response);
 * ```
 */
export declare class PylotAgent {
  /**
   * Launch the interactive setup wizard.
   *
   * Opens browser for OAuth flows, prompts for API keys,
   * and saves credentials to the encrypted secrets vault.
   */
  static init(): Promise<void>
  /** Initialize an agent instance from an existing configuration file. */
  static fromConfig(configPath: string): Promise<PylotAgent>
  /** Create a new agent from a programmatic Config object. */
  static fromOptions(config: Config): PylotAgent
  /**
   * Send a message and get a response.
   *
   * Uses the Rust agent core directly via the library crate.
   */
  chat(message: string): Promise<string>
  /** Run diagnostic checks on the current configuration. */
  static doctor(): Promise<void>
  /** Show agent status and connected services. */
  static status(): Promise<void>
}
/** Access the memory system from Node.js. */
export declare class PylotMemory {
  constructor(dbPath?: string | undefined | null)
  /** Store a memory unit. */
  remember(content: string, memoryType?: string | undefined | null): string
  /** Search memories by keyword. */
  search(query: string, limit?: number | undefined | null): Array<MemorySearchResult>
  /** Get total memory count. */
  count(): number
}
/** Access the skills system from Node.js. */
export declare class PylotSkills {
  constructor(skillsDir?: string | undefined | null)
  /** List all available skills. */
  list(): Array<SkillInfo>
}
/** Access the learning system from Node.js. */
export declare class PylotLearning {
  constructor(dbPath?: string | undefined | null)
  /** List active learned rules. */
  rules(): Array<LearnedRuleInfo>
  /** Submit feedback. */
  feedback(sessionId: string, turnId: string, rating: number, comment?: string | undefined | null): void
}
